"""
SQLAlchemy declarative base and shared mixins.

Strategies (per DATABASE_DESIGN.md §1.2–1.4):
- UUID primary keys via PostgreSQL gen_random_uuid() (pgcrypto)
- TIMESTAMPTZ audit columns in UTC
- Soft delete via deleted_at / deleted_by (NULL = active)
- Optimistic locking via version column
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import DateTime, Integer, MetaData, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column
from sqlalchemy.sql import func

# Naming convention for Alembic autogenerate consistency
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Root declarative base for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """
    UUID v4 primary key generated by PostgreSQL.

    Requires: CREATE EXTENSION pgcrypto (migration 001).
  """

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TenantMixin:
    """Multi-tenant scope — every tenant-scoped row carries tenant_id."""

    @declared_attr
    def tenant_id(cls) -> Mapped[uuid.UUID]:  # noqa: N805
        return mapped_column(
            PG_UUID(as_uuid=True),
            nullable=False,
            index=True,
        )


class TimestampMixin:
    """Immutable-row timestamps (audit logs, delivery logs)."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    created_by: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        nullable=True,
    )


class AuditMixin(TimestampMixin):
    """
    Full audit columns for mutable tenant-scoped tables.

    updated_at is maintained by PostgreSQL trigger public.set_updated_at().
    """

    updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        onupdate=func.now(),
    )
    updated_by: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        nullable=True,
    )
    version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        server_default=text("1"),
    )


class SoftDeleteMixin:
    """
    Soft delete — clinical and financial records retain rows.

    NULL deleted_at means the record is active.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    deleted_by: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        nullable=True,
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None

    def soft_delete(self, *, by: uuid.UUID | None = None) -> None:
        """Mark row as soft-deleted (persist via session.commit())."""
        self.deleted_at = datetime.now(UTC)
        self.deleted_by = by


class TenantAuditableEntity(
    Base,
    UUIDPrimaryKeyMixin,
    TenantMixin,
    AuditMixin,
    SoftDeleteMixin,
):
    """
  Abstract base for standard tenant-scoped business tables.

  Concrete models must set __tablename__ and __table_args__ = {"schema": "..."}.
  """

    __abstract__ = True


class ImmutableTenantEntity(
    Base,
    UUIDPrimaryKeyMixin,
    TenantMixin,
    TimestampMixin,
):
    """Abstract base for append-only tenant-scoped tables (no soft delete / updates)."""

    __abstract__ = True


def active_row_filter(model: type[Any]) -> list[Any]:
    """Return SQLAlchemy criteria excluding soft-deleted rows when applicable."""
    if hasattr(model, "deleted_at"):
        return [model.deleted_at.is_(None)]  # type: ignore[attr-defined]
    return []
