"""Application-wide constants — no environment-specific values."""

APP_NAME = "hms-api"
APP_VERSION = "0.1.0"
SERVICE_NAME = "hms-api"

API_V1_PREFIX = "/api/v1"
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

REQUEST_ID_HEADER = "X-Request-ID"
TENANT_ID_HEADER = "X-Tenant-ID"
TENANT_SLUG_HEADER = "X-Tenant-Slug"

# Auth
JWT_ALGORITHM = "RS256"
JWT_DENYLIST_PREFIX = "jwt:denylist:"
REFRESH_TOKEN_COOKIE = "refresh_token"
AUTH_RATE_LIMIT_PREFIX = "auth:rate:"
LOCKOUT_THRESHOLD = 5
LOCKOUT_MINUTES = 15
MAX_SESSIONS_PER_USER = 5
REFRESH_TOKEN_EXPIRE_DAYS = 7
BCRYPT_ROUNDS = 12

ENVIRONMENT_DEVELOPMENT = "development"
ENVIRONMENT_STAGING = "staging"
ENVIRONMENT_PRODUCTION = "production"
ENVIRONMENT_TEST = "test"

SYSTEM_TENANT_ID = "00000000-0000-0000-0000-000000000001"
